// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// shared_entropy
double shared_entropy(NumericVector x, NumericVector y, int z, int n1, int n2, double w1);
RcppExport SEXP SpadeR_shared_entropy(SEXP xSEXP, SEXP ySEXP, SEXP zSEXP, SEXP n1SEXP, SEXP n2SEXP, SEXP w1SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type z(zSEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type w1(w1SEXP);
    __result = Rcpp::wrap(shared_entropy(x, y, z, n1, n2, w1));
    return __result;
END_RCPP
}
// shared_entropy_sub
double shared_entropy_sub(NumericVector X1, NumericVector X2, NumericVector p1, NumericVector p2, int I, int n1, int n2, double w1);
RcppExport SEXP SpadeR_shared_entropy_sub(SEXP X1SEXP, SEXP X2SEXP, SEXP p1SEXP, SEXP p2SEXP, SEXP ISEXP, SEXP n1SEXP, SEXP n2SEXP, SEXP w1SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type X1(X1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type X2(X2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< int >::type I(ISEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type w1(w1SEXP);
    __result = Rcpp::wrap(shared_entropy_sub(X1, X2, p1, p2, I, n1, n2, w1));
    return __result;
END_RCPP
}
