# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shared_entropy <- function(x, y, z, n1, n2, w1) {
    .Call('SpadeR_shared_entropy', PACKAGE = 'SpadeR', x, y, z, n1, n2, w1)
}

shared_entropy_sub <- function(X1, X2, p1, p2, I, n1, n2, w1) {
    .Call('SpadeR_shared_entropy_sub', PACKAGE = 'SpadeR', X1, X2, p1, p2, I, n1, n2, w1)
}

